package com.prathamngundikere.quviz.util

import com.prathamngundikere.quviz.R
import com.prathamngundikere.quviz.datamodel.Topic

// Functions for different subjects and their topics
// Use the same format as before for adding topics to the list.

fun BiologyTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Cell Biology", R.drawable.cellbiology,null))
    list.add(Topic("Genetics", R.drawable.genetics,null))
    list.add(Topic("Ecology", R.drawable.ecology,null))
    list.add(Topic("Human Anatomy", R.drawable.human,null))
    list.add(Topic("Physiology", R.drawable.physiology,null))
    list.add(Topic("Plant Biology", R.drawable.plantbiology,null))
    list.add(Topic("Microbiology", R.drawable.microbiology,null))
    list.add(Topic("Biochemistry", R.drawable.biochemistry,null))
    list.add(Topic("Immunology", R.drawable.immune,null))
    list.add(Topic("Biotechnology", R.drawable.biotech,null))
    list.add(Topic("Evolution", R.drawable.evo,null))
    // Add more topics here...
    return list.shuffled()
}

fun ChemistryTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Atomic Structure", R.drawable.atomicstructure,null))
    list.add(Topic("Periodic Table", R.drawable.periodictable,null))
    list.add(Topic("Chemical Bonding", R.drawable.chemicalbonding,null))
    list.add(Topic("Stoichiometry", R.drawable.stoichiometry,null))
    list.add(Topic("States of matter", R.drawable.statesofmatter,null))
    list.add(Topic("Acids and Bases", R.drawable.acidsandbases,null))
    list.add(Topic("Redox Rections", R.drawable.redoxreaction,null))
    list.add(Topic("Organic Chemistry", R.drawable.organicchemistry,null))
    list.add(Topic("Thermodynamics Chemistry", R.drawable.thermodynamics,null))
    list.add(Topic("Chemical Equilibrium", R.drawable.chemicalequilirium,null))
    // Add more topics here...
    return list.shuffled()
}

fun PhysicsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Mechanics", R.drawable.mechanics,null))
    list.add(Topic("Thermodynamics Physics", R.drawable.thermodynamics,null))
    list.add(Topic("Electromagnetism", R.drawable.electromagnetism,null))
    list.add(Topic("Optics", R.drawable.optics,null))
    list.add(Topic("Waves and Oscillations", R.drawable.wavesandoscillation,null))
    list.add(Topic("Quantum Mechanics", R.drawable.quantumechanics,null))
    list.add(Topic("Relativity", R.drawable.relativity,null))
    list.add(Topic("Nuclear Physics", R.drawable.nuclearphysics,null))
    list.add(Topic("Particle Physics", R.drawable.particlephysics,null))
    list.add(Topic("Astrophysics", R.drawable.astrophysics,null))
    // Add more topics here...
    return list.shuffled()
}

fun MathematicsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Arithmatic", R.drawable.arithematics,null))
    list.add(Topic("Algebra", R.drawable.algebra,null))
    list.add(Topic("Geometry", R.drawable.geomatry,null))
    list.add(Topic("Trigonometry", R.drawable.trigonometry,null))
    list.add(Topic("Calculus", R.drawable.calculus,null))
    list.add(Topic("Probability", R.drawable.probability,null))
    list.add(Topic("Number Theory", R.drawable.numbertheory,null))
    list.add(Topic("Linear Algebra", R.drawable.linearalgebra,null))
    list.add(Topic("Differential Equaions", R.drawable.differentialequation,null))
    list.add(Topic("Mathematical Logic", R.drawable.mathematicallogic,null))
    // Add more topics here...
    return list.shuffled()
}

fun ComputerScienceTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Programming Concepts", R.drawable.programmingconcepts,null))
    list.add(Topic("Data Structures", R.drawable.datastructures,null))
    list.add(Topic("Algorithms", R.drawable.algorithms,null))
    list.add(Topic("Object-Oriented Programming", R.drawable.objectoriented,null))
    list.add(Topic("Databases", R.drawable.databases,null))
    list.add(Topic("Computer Networks", R.drawable.computernetworks,null))
    list.add(Topic("Operating Systems", R.drawable.operatingsystem,null))
    list.add(Topic("Web Development", R.drawable.webdevelopment,null))
    list.add(Topic("Artificial Intelligence", R.drawable.ai,null))
    list.add(Topic("Cybersecurity", R.drawable.cybersecurity,null))
    // Add more topics here...
    return list.shuffled()
}

fun HistoryTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Ancient Civilizations", R.drawable.ancientcivilization,null))
    list.add(Topic("World Wars", R.drawable.worldwars,null))
    list.add(Topic("Renaissance", R.drawable.renaissance,null))
    list.add(Topic("Colonialism and Imperialism", R.drawable.colonialism,null))
    list.add(Topic("Industrial Revolution", R.drawable.industrialrevolution,null))
    list.add(Topic("Cold War", R.drawable.coldwars,null))
    list.add(Topic("Civil Rights Movement", R.drawable.civilrightmovement,null))
    list.add(Topic("Globalization", R.drawable.globalization,null))
    list.add(Topic("Revolutionary Movements", R.drawable.revolutionarymovements,null))
    list.add(Topic("Decolonization", R.drawable.decolonization,null))
    // Add more topics here...
    return list.shuffled()
}

fun CivicsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Types of Government", R.drawable.typesofgvernment,null))
    list.add(Topic("Constitution and Rights", R.drawable.constitutionalrights,null))
    list.add(Topic("Citizenship and Democracy", R.drawable.citizenship,null))
    list.add(Topic("Political Systems", R.drawable.politicalsystem,null))
    list.add(Topic("Law and Justice", R.drawable.lawandjustice,null))
    list.add(Topic("Elections and Voting", R.drawable.elections,null))
    list.add(Topic("Public Policy", R.drawable.publicpolicy,null))
    list.add(Topic("International Relations", R.drawable.internationalrelation,null))
    list.add(Topic("Human Rights", R.drawable.humanrights,null))
    list.add(Topic("Civic Responsibilities", R.drawable.civicresponcibility,null))
    // Add more topics here...
    return list.shuffled()
}

fun GeographyTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Physical Geography", R.drawable.physicalgeography,null))
    list.add(Topic("Human Geography", R.drawable.humangeography,null))
    list.add(Topic("World Geography", R.drawable.worldgeography,null))
    list.add(Topic("Cultural Geography", R.drawable.culturalgeography,null))
    list.add(Topic("Environmental Geography", R.drawable.environmentalgeography,null))
    list.add(Topic("Geographic Information Systems (GIS)", R.drawable.gis,null))
    list.add(Topic("Population and Migration", R.drawable.populationandmigration,null))
    list.add(Topic("Landforms and Biomes", R.drawable.landformsandbiomes,null))
    list.add(Topic("Climate and Weather", R.drawable.climateandweather,null))
    list.add(Topic("Natural Resources", R.drawable.naturalresources,null))
    // Add more topics here...
    return list.shuffled()
}

fun CommerceTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Business Studies", R.drawable.businessstudies,null))
    list.add(Topic("Accounting", R.drawable.accounting,null))
    list.add(Topic("Economics", R.drawable.economics,null))
    list.add(Topic("Marketing", R.drawable.marketing,null))
    list.add(Topic("Finance", R.drawable.finance,null))
    list.add(Topic("Entrepreneurship", R.drawable.entrepenerur,null))
    list.add(Topic("Supply Chain Management", R.drawable.supplychainmanagement,null))
    list.add(Topic("International Trade", R.drawable.internationaltrade,null))
    list.add(Topic("Business Law", R.drawable.businesslaw,null))
    list.add(Topic("Financial Management", R.drawable.financialmanagement,null))
    // Add more topics here...
    return list.shuffled()
}

fun StatisticsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Descriptive Statistics", R.drawable.descriptivestatistics,null))
    list.add(Topic("Probability Distributions", R.drawable.probabilitydistribution,null))
    list.add(Topic("Hypothesis Testing", R.drawable.hypothesistesting,null))
    list.add(Topic("Regression Analysis", R.drawable.regressionanalysis,null))
    list.add(Topic("Sampling Techniques", R.drawable.samplingtechniques,null))
    list.add(Topic("Statistical Modeling", R.drawable.statisticalmodelling,null))
    list.add(Topic("Experimental Design", R.drawable.experimentaldesign,null))
    list.add(Topic("Data Visualization", R.drawable.datavisualization,null))
    list.add(Topic("Statistical Software", R.drawable.statisticalsoftware,null))
    list.add(Topic("Time Series Analysis", R.drawable.timeseriesanalysis,null))
    // Add more topics here...
    return list.shuffled()
}

fun MechanicalTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Statics and Dynamics", R.drawable.staticsanddynamiscs,null))
    list.add(Topic("Thermodynamics", R.drawable.thermodynamics,null))
    list.add(Topic("Fluid Mechanics", R.drawable.fluidmechanics,null))
    list.add(Topic("Heat Transfer", R.drawable.heattransfer,null))
    list.add(Topic("Materials Science", R.drawable.materialscience,null))
    list.add(Topic("Mechanics of Machines", R.drawable.mechanicsofmachine,null))
    list.add(Topic("Manufacturing Processes", R.drawable.manufacturingprocess,null))
    list.add(Topic("Automotive Engineering", R.drawable.automotivenginnering,null))
    list.add(Topic("Robotics and Automation", R.drawable.roboticsandautomation,null))
    list.add(Topic("Engineering Design", R.drawable.engineeringdesign,null))
    // Add more topics here...
    return list.shuffled()
}

fun CivilTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Structural Engineering", R.drawable.structuralenginnereing,null))
    list.add(Topic("Geotechnical Engineering", R.drawable.geotechnicalenginnering,null))
    list.add(Topic("Transportation Engineering", R.drawable.transpotationenginnereing,null))
    list.add(Topic("Environmental Engineering", R.drawable.environmentalenginnering,null))
    list.add(Topic("Water Resources Engineering", R.drawable.waterresourcesenginnering,null))
    list.add(Topic("Construction Management", R.drawable.constructionengineering,null))
    list.add(Topic("Urban Planning", R.drawable.urbanplanning,null))
    list.add(Topic("Surveying and Mapping", R.drawable.surveyingandmapping,null))
    list.add(Topic("Infrastructure Development", R.drawable.infrastructuredevelopment,null))
    list.add(Topic("Building Materials and Technology", R.drawable.buildingmaterials,null))
    // Add more topics here...
    return list.shuffled()
}

fun ElectronicsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Analog Electronics", R.drawable.analogelectronics,null))
    list.add(Topic("Digital Electronics", R.drawable.digitalelectronics,null))
    list.add(Topic("Microelectronics", R.drawable.microelectronics,null))
    list.add(Topic("Electronic Circuits", R.drawable.electronicircuits,null))
    list.add(Topic("Signal Processing", R.drawable.signalprocccing,null))
    list.add(Topic("Communication Systems", R.drawable.communicationsystem,null))
    list.add(Topic("Power Electronics", R.drawable.powerelectronics,null))
    list.add(Topic("Embedded Systems", R.drawable.embeddedsystem,null))
    list.add(Topic("Control Systems", R.drawable.controlsystem,null))
    list.add(Topic("VLSI Design", R.drawable.vlsi,null))
    // Add more topics here...
    return list.shuffled()
}

fun MoviesTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Action", R.drawable.action,null))
    list.add(Topic("Comedy", R.drawable.comedy,null))
    list.add(Topic("Drama", R.drawable.drama,null))
    list.add(Topic("Romance", R.drawable.romance,null))
    list.add(Topic("Horror", R.drawable.horror,null))
    list.add(Topic("Thriller", R.drawable.thriller,null))
    list.add(Topic("Science Fiction", R.drawable.sciencefiction,null))
    list.add(Topic("Fantasy", R.drawable.fantasy,null))
    list.add(Topic("Animation", R.drawable.animation,null))
    list.add(Topic("Documentary", R.drawable.documentry,null))
    // Add more topics here...
    return list.shuffled()
}

fun SportsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Football", R.drawable.football,null))
    list.add(Topic("Basketball", R.drawable.basketball,null))
    list.add(Topic("Tennis", R.drawable.tennis,null))
    list.add(Topic("Cricket", R.drawable.cricket,null))
    list.add(Topic("Golf", R.drawable.golf,null))
    list.add(Topic("Baseball", R.drawable.baseball,null))
    list.add(Topic("Swimming", R.drawable.swimming,null))
    list.add(Topic("Athletics", R.drawable.athletics,null))
    list.add(Topic("Volleyball", R.drawable.vollyball,null))
    list.add(Topic("Hockey", R.drawable.hockey,null))
    // Add more topics here...
    return list.shuffled()
}

fun CurrentAffairsTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Politics", R.drawable.politics,null))
    list.add(Topic("Economy", R.drawable.economy,null))
    list.add(Topic("Science and Technology", R.drawable.scienceandtech,null))
    list.add(Topic("Environment", R.drawable.environment,null))
    list.add(Topic("Sports", R.drawable.sports,null))
    list.add(Topic("Health", R.drawable.health,null))
    list.add(Topic("International Relations", R.drawable.internationalrelation,null))
    list.add(Topic("Social Issues", R.drawable.socialissue,null))
    list.add(Topic("Business", R.drawable.business,null))
    list.add(Topic("Education", R.drawable.education,null))
    // Add more topics here...
    return list.shuffled()
}

fun FashionTopics(): List<Topic> {
    val list = mutableListOf<Topic>()
    list.add(Topic("Clothing Styles", R.drawable.clothingstyles,null))
    list.add(Topic("Fashion Trends", R.drawable.fashiontrends,null))
    list.add(Topic("Fashion Designers", R.drawable.fashiondesignors,null))
    list.add(Topic("Fashion Accessories", R.drawable.fashionaccessoryes,null))
    list.add(Topic("Fashion Shows", R.drawable.fashionshow,null))
    list.add(Topic("Beauty and Makeup", R.drawable.beautyandmakeup,null))
    list.add(Topic("Fashion Brands", R.drawable.fashionbrands,null))
    list.add(Topic("Hairstyles", R.drawable.hairstyle,null))
    list.add(Topic("Fashion Photography", R.drawable.fashionphotography,null))
    list.add(Topic("Fashion Magazines", R.drawable.fashionmagazines,null))
    // Add more topics here...
    return list.shuffled()
}
fun searchlist(): List<Topic>{
    val list = mutableListOf<Topic>()
    list.add(Topic("Cell Biology", R.drawable.cellbiology,null))
    list.add(Topic("Genetics", R.drawable.genetics,null))
    list.add(Topic("Ecology", R.drawable.ecology,null))
    list.add(Topic("Human Anatomy", R.drawable.human,null))
    list.add(Topic("Physiology", R.drawable.physiology,null))
    list.add(Topic("Plant Biology", R.drawable.plantbiology,null))
    list.add(Topic("Microbiology", R.drawable.microbiology,null))
    list.add(Topic("Biochemistry", R.drawable.biochemistry,null))
    list.add(Topic("Immunology", R.drawable.immune,null))
    list.add(Topic("Biotechnology", R.drawable.biotech,null))
    list.add(Topic("Evolution", R.drawable.evo,null))
    list.add(Topic("Atomic Structure", R.drawable.atomicstructure,null))
    list.add(Topic("Periodic Table", R.drawable.periodictable,null))
    list.add(Topic("Chemical Bonding", R.drawable.chemicalbonding,null))
    list.add(Topic("Stoichiometry", R.drawable.stoichiometry,null))
    list.add(Topic("States of matter", R.drawable.statesofmatter,null))
    list.add(Topic("Acids and Bases", R.drawable.acidsandbases,null))
    list.add(Topic("Redox Rections", R.drawable.redoxreaction,null))
    list.add(Topic("Organic Chemistry", R.drawable.organicchemistry,null))
    list.add(Topic("Thermodynamics Chemistry", R.drawable.thermodynamics,null))
    list.add(Topic("Chemical Equilibrium", R.drawable.chemicalequilirium,null))
    list.add(Topic("Mechanics", R.drawable.mechanics,null))
    list.add(Topic("Thermodynamics Physics", R.drawable.thermodynamics,null))
    list.add(Topic("Electromagnetism", R.drawable.electromagnetism,null))
    list.add(Topic("Optics", R.drawable.optics,null))
    list.add(Topic("Waves and Oscillations", R.drawable.wavesandoscillation,null))
    list.add(Topic("Quantum Mechanics", R.drawable.quantumechanics,null))
    list.add(Topic("Relativity", R.drawable.relativity,null))
    list.add(Topic("Nuclear Physics", R.drawable.nuclearphysics,null))
    list.add(Topic("Particle Physics", R.drawable.particlephysics,null))
    list.add(Topic("Astrophysics", R.drawable.astrophysics,null))
    list.add(Topic("Arithmatic", R.drawable.arithematics,null))
    list.add(Topic("Algebra", R.drawable.algebra,null))
    list.add(Topic("Geometry", R.drawable.geomatry,null))
    list.add(Topic("Trigonometry", R.drawable.trigonometry,null))
    list.add(Topic("Calculus", R.drawable.calculus,null))
    list.add(Topic("Probability", R.drawable.probability,null))
    list.add(Topic("Number Theory", R.drawable.numbertheory,null))
    list.add(Topic("Linear Algebra", R.drawable.linearalgebra,null))
    list.add(Topic("Differential Equaions", R.drawable.differentialequation,null))
    list.add(Topic("Mathematical Logic", R.drawable.mathematicallogic,null))
    list.add(Topic("Programming Concepts", R.drawable.programmingconcepts,null))
    list.add(Topic("Data Structures", R.drawable.datastructures,null))
    list.add(Topic("Algorithms", R.drawable.algorithms,null))
    list.add(Topic("Object-Oriented Programming", R.drawable.objectoriented,null))
    list.add(Topic("Databases", R.drawable.databases,null))
    list.add(Topic("Computer Networks", R.drawable.computernetworks,null))
    list.add(Topic("Operating Systems", R.drawable.operatingsystem,null))
    list.add(Topic("Web Development", R.drawable.webdevelopment,null))
    list.add(Topic("Artificial Intelligence", R.drawable.ai,null))
    list.add(Topic("Cybersecurity", R.drawable.cybersecurity,null))
    list.add(Topic("Ancient Civilizations", R.drawable.ancientcivilization,null))
    list.add(Topic("World Wars", R.drawable.worldwars,null))
    list.add(Topic("Renaissance", R.drawable.renaissance,null))
    list.add(Topic("Colonialism and Imperialism", R.drawable.colonialism,null))
    list.add(Topic("Industrial Revolution", R.drawable.industrialrevolution,null))
    list.add(Topic("Cold War", R.drawable.coldwars,null))
    list.add(Topic("Civil Rights Movement", R.drawable.civilrightmovement,null))
    list.add(Topic("Globalization", R.drawable.globalization,null))
    list.add(Topic("Revolutionary Movements", R.drawable.revolutionarymovements,null))
    list.add(Topic("Decolonization", R.drawable.decolonization,null))
    list.add(Topic("Types of Government", R.drawable.typesofgvernment,null))
    list.add(Topic("Constitution and Rights", R.drawable.constitutionalrights,null))
    list.add(Topic("Citizenship and Democracy", R.drawable.citizenship,null))
    list.add(Topic("Political Systems", R.drawable.politicalsystem,null))
    list.add(Topic("Law and Justice", R.drawable.lawandjustice,null))
    list.add(Topic("Elections and Voting", R.drawable.elections,null))
    list.add(Topic("Public Policy", R.drawable.publicpolicy,null))
    list.add(Topic("International Relations", R.drawable.internationalrelation,null))
    list.add(Topic("Human Rights", R.drawable.humanrights,null))
    list.add(Topic("Civic Responsibilities", R.drawable.civicresponcibility,null))
    list.add(Topic("Physical Geography", R.drawable.physicalgeography,null))
    list.add(Topic("Human Geography", R.drawable.humangeography,null))
    list.add(Topic("World Geography", R.drawable.worldgeography,null))
    list.add(Topic("Cultural Geography", R.drawable.culturalgeography,null))
    list.add(Topic("Environmental Geography", R.drawable.environmentalgeography,null))
    list.add(Topic("Geographic Information Systems (GIS)", R.drawable.gis,null))
    list.add(Topic("Population and Migration", R.drawable.populationandmigration,null))
    list.add(Topic("Landforms and Biomes", R.drawable.landformsandbiomes,null))
    list.add(Topic("Climate and Weather", R.drawable.climateandweather,null))
    list.add(Topic("Natural Resources", R.drawable.naturalresources,null))
    list.add(Topic("Business Studies", R.drawable.businessstudies,null))
    list.add(Topic("Accounting", R.drawable.accounting,null))
    list.add(Topic("Economics", R.drawable.economics,null))
    list.add(Topic("Marketing", R.drawable.marketing,null))
    list.add(Topic("Finance", R.drawable.finance,null))
    list.add(Topic("Entrepreneurship", R.drawable.entrepenerur,null))
    list.add(Topic("Supply Chain Management", R.drawable.supplychainmanagement,null))
    list.add(Topic("International Trade", R.drawable.internationaltrade,null))
    list.add(Topic("Business Law", R.drawable.businesslaw,null))
    list.add(Topic("Financial Management", R.drawable.financialmanagement,null))
    list.add(Topic("Descriptive Statistics", R.drawable.descriptivestatistics,null))
    list.add(Topic("Probability Distributions", R.drawable.probabilitydistribution,null))
    list.add(Topic("Hypothesis Testing", R.drawable.hypothesistesting,null))
    list.add(Topic("Regression Analysis", R.drawable.regressionanalysis,null))
    list.add(Topic("Sampling Techniques", R.drawable.samplingtechniques,null))
    list.add(Topic("Statistical Modeling", R.drawable.statisticalmodelling,null))
    list.add(Topic("Experimental Design", R.drawable.experimentaldesign,null))
    list.add(Topic("Data Visualization", R.drawable.datavisualization,null))
    list.add(Topic("Statistical Software", R.drawable.statisticalsoftware,null))
    list.add(Topic("Time Series Analysis", R.drawable.timeseriesanalysis,null))
    list.add(Topic("Statics and Dynamics", R.drawable.staticsanddynamiscs,null))
    list.add(Topic("Thermodynamics", R.drawable.thermodynamics,null))
    list.add(Topic("Fluid Mechanics", R.drawable.fluidmechanics,null))
    list.add(Topic("Heat Transfer", R.drawable.heattransfer,null))
    list.add(Topic("Materials Science", R.drawable.materialscience,null))
    list.add(Topic("Mechanics of Machines", R.drawable.mechanicsofmachine,null))
    list.add(Topic("Manufacturing Processes", R.drawable.manufacturingprocess,null))
    list.add(Topic("Automotive Engineering", R.drawable.automotivenginnering,null))
    list.add(Topic("Robotics and Automation", R.drawable.roboticsandautomation,null))
    list.add(Topic("Engineering Design", R.drawable.engineeringdesign,null))
    list.add(Topic("Structural Engineering", R.drawable.structuralenginnereing,null))
    list.add(Topic("Geotechnical Engineering", R.drawable.geotechnicalenginnering,null))
    list.add(Topic("Transportation Engineering", R.drawable.transpotationenginnereing,null))
    list.add(Topic("Environmental Engineering", R.drawable.environmentalenginnering,null))
    list.add(Topic("Water Resources Engineering", R.drawable.waterresourcesenginnering,null))
    list.add(Topic("Construction Management", R.drawable.constructionengineering,null))
    list.add(Topic("Urban Planning", R.drawable.urbanplanning,null))
    list.add(Topic("Surveying and Mapping", R.drawable.surveyingandmapping,null))
    list.add(Topic("Infrastructure Development", R.drawable.infrastructuredevelopment,null))
    list.add(Topic("Building Materials and Technology", R.drawable.buildingmaterials,null))
    list.add(Topic("Analog Electronics", R.drawable.analogelectronics,null))
    list.add(Topic("Digital Electronics", R.drawable.digitalelectronics,null))
    list.add(Topic("Microelectronics", R.drawable.microelectronics,null))
    list.add(Topic("Electronic Circuits", R.drawable.electronicircuits,null))
    list.add(Topic("Signal Processing", R.drawable.signalprocccing,null))
    list.add(Topic("Communication Systems", R.drawable.communicationsystem,null))
    list.add(Topic("Power Electronics", R.drawable.powerelectronics,null))
    list.add(Topic("Embedded Systems", R.drawable.embeddedsystem,null))
    list.add(Topic("Control Systems", R.drawable.controlsystem,null))
    list.add(Topic("VLSI Design", R.drawable.vlsi,null))
    list.add(Topic("Football", R.drawable.football,null))
    list.add(Topic("Basketball", R.drawable.basketball,null))
    list.add(Topic("Tennis", R.drawable.tennis,null))
    list.add(Topic("Cricket", R.drawable.cricket,null))
    list.add(Topic("Golf", R.drawable.golf,null))
    list.add(Topic("Baseball", R.drawable.baseball,null))
    list.add(Topic("Swimming", R.drawable.swimming,null))
    list.add(Topic("Athletics", R.drawable.athletics,null))
    list.add(Topic("Volleyball", R.drawable.vollyball,null))
    list.add(Topic("Hockey", R.drawable.hockey,null))
    list.add(Topic("Clothing Styles", R.drawable.clothingstyles,null))
    list.add(Topic("Fashion Trends", R.drawable.fashiontrends,null))
    list.add(Topic("Fashion Designers", R.drawable.fashiondesignors,null))
    list.add(Topic("Fashion Accessories", R.drawable.fashionaccessoryes,null))
    list.add(Topic("Fashion Shows", R.drawable.fashionshow,null))
    list.add(Topic("Beauty and Makeup", R.drawable.beautyandmakeup,null))
    list.add(Topic("Fashion Brands", R.drawable.fashionbrands,null))
    list.add(Topic("Hairstyles", R.drawable.hairstyle,null))
    list.add(Topic("Fashion Photography", R.drawable.fashionphotography,null))
    list.add(Topic("Fashion Magazines", R.drawable.fashionmagazines,null))
    return list.shuffled()
}